site_name: Guide to the MPPW
nav:
  - Home: index.md
  - Tutorial:
      - "Create a Project": tutorial/create_a_project.md
      - "Add Operations": tutorial/add_operations.md
      - "Modify Schema": tutorial/modify_schema.md
  - Roadmap: roadmap.md
  - User Interface: notes.md
theme: readthedocs
