site_name: Guide to the MPPW
nav:
  - Home: index.md
  - Deployment: deploy.md
  - Roadmap: roadmap.md
  - Release Notes: release_notes.md
  - Tutorial:
      - "Create a Project": tutorial/create_a_project.md
      - "Add Operations": tutorial/add_operations.md
      - "Modify Schema": tutorial/modify_schema.md
  - Data Integration:
      - "Data Entry": data_integration/data_entry.md
      - "Sensor Data and Automation": data_integration/sensor_data.md
theme: readthedocs
