[tool.poetry]
name = "mppw"
version = "0.2.0"
description = ""
authors = ["ASCC <ascc@maine.edu>"]
include = ["MPPW_RELEASE_NOTES.md"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.68.2"
motor = "^2.5.1"
argh = "^0.26.2"
uvicorn = {extras = ["standard"], version = "^0.15.0"}
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-multipart = "^0.0.5"
furl = "^2.1.3"
toml = "^0.10.2"
docker-compose = "^1.29.2"
pymongo-migrate = "^0.11.0"
aiofiles = "^0.8.0"
arrow = "^1.2.2"
dbvox = { git = "git@gitlab.composites.umaine.edu:DataProcessing/dbvox.git", branch = "main" }
json-stream = "^1.3.0"
# START for pcl
numpy = "1.21"
# END for pcl
pyjson5 = "^1.6.1"
importlib-metadata = "^4.11.3"
networkx = "^2.8.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

# START for (fff_)analysis
#notebook = "^6.4.8"
#matplotlib = "^3.5.1"
#ipympl = "^0.8.7"
# END for (fff_)analysis
black = {version = "^22.3.0", allow-prereleases = true}


[tool.poetry.scripts]
mppw-docker = "scripts.docker:main"
mppw-migrations = "scripts.migrations:main"
mppw-app = "scripts.app:main"

[tool.black]
extend-exclude = '''
(^/(containers|fff_post|mppw/pcl))
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
