version: "3"
services:
  mppapi:
    restart: always
    image: ascc/mppapi:dev
    ports:
      - "8001:8000"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
      MONGODB_URL: mongodb://mongodb:27017
      MONGODB_USERNAME: app_user
      MONGODB_PASSWORD: app_password
  mongodb:
    image: mongo:4.4.6
    volumes:
      - data-db:/data/db
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=app_user
      - MONGO_INITDB_ROOT_PASSWORD=app_password
      - MONGO_INITDB_DATABASE=admin

volumes:
  data-db:
